import Path from 'path'
import { lowerFirst, camelCase, upperFirst } from 'lodash'
import * as childProcess from 'child_process'

import * as Tree from '../tree'
import { Resource, Message, Var, VarType } from '../parser'

async function main(resources: Array<[string, Promise<Resource>]>, write: (path: string, data: string) => Promise<void>): Promise<void> {
    const outputPaths: string[] = await Promise.all(resources.map(async ([shortPath, pending]) => {
        const resource = await pending

        const parsed = Path.parse(shortPath)
        const outputPath = Path.join('localization', parsed.dir, parsed.name)
        // console.log({ parsed, outputPath })
        const output = await prettier(genResource(resource.messages))
        await write(`${outputPath}.tsx`, output)
        return outputPath
    }))
    await write('localization.ts', await prettier(genIndex(outputPaths)))
}

function genIndex(outputPaths: string[]): string {
    const root = Tree.build(outputPaths.map(m => m.split(Path.sep).filter(i => i)))
    const tree = root.nodes.localization
    return (`\
${genHeader}

${outputPaths.map(m => `import * as ${camelCase(m)} from ${JSON.stringify(['.'].concat(m.split(Path.sep)).join('/'))}`).join("\n")}

${genModuleTree(tree)}
`)
}
function genModuleTree(tree: Tree.Node): string {
    const leaves: Array<[string, string]> = tree.leaves.map(l => [l, camelCase(Path.join(...tree.path.concat([l])))])
    const nodes: Array<[string, string]> = Object.entries(tree.nodes).map(([name, n]) => [name, `{${genModuleTree(n)}}`])
    return [...leaves, ...nodes].map(([lval, rval]) => `export const ${lowerFirst(camelCase(lval))} = ${rval}`).join(`,\n${Array((tree.path.length - 1) * 4).fill(' ')}`)
}

async function prettier(input: string): Promise<string> {
    return new Promise((resolve, reject) => {
        const proc = childProcess.exec("prettier --stdin-filepath localization.tsx", {}, (error, stdout, stderr) => {
            if (error) {
                console.error(stderr)
                return reject(error)
            }
            return resolve(stdout)
        })
        if (!proc?.stdin) {
            return reject('failed to spawn prettier')
        }
        // console.error(input)
        const stdin = proc.stdin // make typescript happy
        stdin.write(input, () => {
            stdin.end()
        })
    })
}

const genHeader = '/** File auto-generated by `@erosson/fluent-typesafe`. Do not edit! */'

function genResource(messages: Message[]) {
    return (`\
${genHeader}
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import __React from 'react'
import * as __L from '@fluent/react'

// https://github.com/projectfluent/fluent.js/blob/master/fluent-react/src/localized.ts
type __props = Omit<__L.LocalizedProps, 'id' | 'vars' | 'attrs'>

${messages.map(genMessage).join("\n\n")}
`
    )
}
function genMessage(message: Message) {
    return (`\
export function ${upperFirst(camelCase(message.id))}(props: __props${genVars(message.placeholders)}${genAttrs(message.attributes)}): JSX.Element {
    return <__L.Localized id="${message.id}" {...props} />
}
`)
}

function genVars(placeholders: Var[]): string {
    return placeholders.length
        ? ` & {vars: {${placeholders.map(genVarType).join(', ')}}}`
        : ''
}

function genVarType(v: Var) {
    switch (v.type) {
        case VarType.STRING: return `${v.name}: string`
        case VarType.NUMBER: return `${v.name}: number`
        case VarType.DATETIME: return `${v.name}: Date`
    }
}

function genAttrs(attributes: Set<string>): string {
    return attributes.size
        ? ` & {attrs: {${Array.from(attributes.values()).map(a => `${JSON.stringify(a)}: boolean`).join(', ')}}}`
        : ''
}

export default main